export const FEED_GROUPS = {
  a: [
    'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml','https://rss.nytimes.com/services/xml/rss/nyt/US.xml','https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml','https://rss.nytimes.com/services/xml/rss/nyt/World.xml','https://feeds.bbci.co.uk/news/rss.xml','https://feeds.bbci.co.uk/news/world/rss.xml','https://feeds.bbci.co.uk/news/us_and_canada/rss.xml','https://feeds.bbci.co.uk/news/politics/rss.xml','https://www.theguardian.com/world/rss','https://www.theguardian.com/us-news/rss','https://www.theguardian.com/politics/rss','https://www.theguardian.com/international/rss','https://feeds.npr.org/1001/rss.xml','https://feeds.npr.org/1004/rss.xml','https://feeds.npr.org/1003/rss.xml','https://www.pbs.org/newshour/feeds/rss/headlines','https://www.pbs.org/newshour/feeds/rss/politics','https://www.cbsnews.com/latest/rss/main','https://www.cbsnews.com/latest/rss/us','https://abcnews.go.com/abcnews/topstories','https://abcnews.go.com/abcnews/usheadlines','https://rss.dw.com/xml/rss-en-all','https://rss.dw.com/xml/rss-en-world','https://www.aljazeera.com/xml/rss/all.xml','https://www.france24.com/en/rss','https://www.voanews.com/api/zmg_eli','https://feeds.skynews.com/feeds/rss/world.xml','https://feeds.skynews.com/feeds/rss/us.xml','https://www.euronews.com/rss?level=theme&name=news','https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml'
  ],
  b: [
    'https://www.marketwatch.com/rss/topstories','https://www.marketwatch.com/rss/marketpulse','https://feeds.a.dj.com/rss/RSSMarketsMain.xml','https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml','https://rss.nytimes.com/services/xml/rss/nyt/Business.xml','https://feeds.bbci.co.uk/news/business/rss.xml','https://www.theguardian.com/business/rss','https://www.cbsnews.com/latest/rss/moneywatch','https://www.investing.com/rss/news.rss','https://www.investing.com/rss/market_overview.rss','https://www.investing.com/rss/stock.rss','https://www.investing.com/rss/commodities.rss','https://www.investing.com/rss/forex.rss','https://www.investing.com/rss/economic_indicator.rss','https://www.investing.com/rss/central_banks.rss','https://www.investing.com/rss/stock_market.rss','https://www.cnbc.com/id/100003114/device/rss/rss.html','https://www.cnbc.com/id/10001147/device/rss/rss.html','https://www.cnbc.com/id/15839069/device/rss/rss.html','https://www.ft.com/rss/home/us','https://fortune.com/feed/fortune-feeds/?id=3230629','https://rss.dw.com/xml/rss-en-business','https://news.google.com/rss/search?q=business%20markets&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=stocks%20wall%20street&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=oil%20gold%20commodities&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=federal%20reserve%20inflation&hl=en-US&gl=US&ceid=US:en','https://finance.yahoo.com/news/rssindex','https://cointelegraph.com/rss','https://coindesk.com/arc/outboundfeeds/rss/','https://decrypt.co/feed'
  ],
  c: [
    'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml','https://rss.nytimes.com/services/xml/rss/nyt/Science.xml','https://feeds.bbci.co.uk/news/technology/rss.xml','https://www.theguardian.com/technology/rss','https://www.theguardian.com/science/rss','https://www.technologyreview.com/feed/','https://www.engadget.com/rss.xml','https://www.theverge.com/rss/index.xml','https://www.wired.com/feed/rss','https://arstechnica.com/feed/','https://techcrunch.com/feed/','https://www.sciencedaily.com/rss/top.xml','https://www.sciencedaily.com/rss/health_medicine.xml','https://www.sciencedaily.com/rss/earth_climate.xml','https://www.sciencedaily.com/rss/space_time.xml','https://rss.dw.com/xml/rss-en-science','https://www.nasa.gov/news-release/feed/','https://www.nasa.gov/technology/feed/','https://news.mit.edu/rss/topic/artificial-intelligence2','https://www.microsoft.com/en-us/research/feed/','https://openai.com/news/rss.xml','https://blog.google/technology/ai/rss/','https://news.google.com/rss/search?q=artificial%20intelligence&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=cybersecurity&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=space%20nasa&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=climate%20science&hl=en-US&gl=US&ceid=US:en'
  ],
  d: [
    'https://rss.nytimes.com/services/xml/rss/nyt/Health.xml','https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml','https://feeds.bbci.co.uk/sport/rss.xml','https://www.theguardian.com/sport/rss','https://www.espn.com/espn/rss/news','https://www.espncricinfo.com/rss/content/story/feeds/0.xml','https://www.pbs.org/newshour/feeds/rss/health','https://feeds.feedburner.com/time/topstories','https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml','https://rss.nytimes.com/services/xml/rss/nyt/Movies.xml','https://rss.nytimes.com/services/xml/rss/nyt/Travel.xml','https://www.theguardian.com/culture/rss','https://www.theguardian.com/film/rss','https://www.theguardian.com/music/rss','https://www.npr.org/rss/rss.php?id=1008','https://www.npr.org/rss/rss.php?id=1039','https://news.google.com/rss/search?q=weather%20alerts&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=conflict%20war&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=earthquake%20wildfire%20flood&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=pandemic%20health%20alerts&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=military%20events&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=India%20news&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=China%20news&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=Europe%20news&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=Middle%20East%20news&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=Africa%20news&hl=en-US&gl=US&ceid=US:en','https://news.google.com/rss/search?q=Latin%20America%20news&hl=en-US&gl=US&ceid=US:en'
  ]
};
export const ALL_FEEDS = [...FEED_GROUPS.a, ...FEED_GROUPS.b, ...FEED_GROUPS.c, ...FEED_GROUPS.d];
